set(CMAKE_SYSTEM_NAME Web)
set(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_C_COMPILER		"emcc")
set(CMAKE_CXX_COMPILER "em++")
set(CMAKE_AR "emar")
set(CMAKE_RANLIB "emranlib")

set(triple "asmjs-unknown-emscripten")

set(CMAKE_CROSS_COMPILING TRUE)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
